name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/workflow-B.yml@linyangao42-patch-1
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}
